### PR TITLE
Power_of_Two.java

### LINKED ISSUE #56: 3.Check wether a number is power of two(BIT-MANIPULATION)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation- -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
[https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be](https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be)

### PR DESCRIPTION
**Pull request by 2000shivam659**
Fixes #56 
@ujju20  please review it.

### CODE REVIEW

**Comment by ujju20** [comment]
Good Work 
But You don't have to make a new PR you could have made changes in the old PR.

**Comment by 2000shivam659** [comment]
@ujju20 Please add labels.

**Comment by 2000shivam659** [comment]
@ujju20 I mean levels i.e., level-2.

**Comment by 2000shivam659** [comment]
I think if you do not add levels then it will not be counted towards my points.

**Pull request merged**
