### PR TITLE
Create 4_Palindrome_Linked_List.cpp under LGMSOC21

### LINKED ISSUE #68: 4. Palindrome Linked List (LINKED LIST)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Linked List-> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

### PR DESCRIPTION
**Pull request by AtrikGit6174**
Fixes #68 
@ujju20 Kindly Check

### CODE REVIEW

**Comment by ujju20** [comment]
Has Your solution been submitted on leetcode with Accepted Status?

**Comment by AtrikGit6174** [comment]
Yes... In fact after writing the main, I checked it on CodeChef IDE and it worked.
Is there any issue about the code?

**Comment by ujju20** [comment]
> Yes... In fact after writing the main, I checked it on CodeChef IDE and it worked.
> Is there any issue about the code?

No No I was just Confirming.
Keep up the Good Work 👍🏻

**Comment by AtrikGit6174** [comment]
Thanks a lot 😃

**Pull request merged**
