### PR TITLE
6. Happy Number (MATH) #198

### PR DESCRIPTION
**Pull request by monishamandal02**

### CODE REVIEW

**Comment by YashThakare** [comment]
Hi @monishamandal02, Please create different PR for different questions ( 1 PR for 1 question)

**Comment by monishamandal02** [comment]
Alright

**Comment by YashThakare** [comment]
> Removed ValidSquare.cpp

Ok

**Review by YashThakare — CHANGES_REQUESTED** [review]
Hi @monishamandal02 , Please add one more example. Code is perfect.

**Comment by monishamandal02** [comment]
Done

**Pull request merged**
