### PR TITLE
Power Of Two (README.md)

### LINKED ISSUE #56: 3.Check wether a number is power of two(BIT-MANIPULATION)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation- -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
[https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be](https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be)

### PR DESCRIPTION
**Pull request by 2000shivam659**
Fixes #56 
Easy Java Solution for "Power Of Two" using bit-manipulation.

### CODE REVIEW

**Comment by ujju20** [comment]
Hey @2000shivam659 You have written the code in readme.md but it is clearly mentioned in the contribution guidelines that the extension of file should be .cpp or .py or .java and also you have created another folder in the language folder which is not required.
Read Contribution guidelines again and make the required chenges.

**Review by ujju20 — CHANGES_REQUESTED** [review]
Make the required Changes @2000shivam659

**Comment by 2000shivam659** [comment]
I have followed the steps as shown in video, thats why i have created a folder in language folder.

**Comment by ujju20** [comment]
> I have followed the steps as shown in video, thats why i have created a folder in language folder. @ujju20

Check the Updated Video

**Pull request closed without merging**
