### PR TITLE
Encode and Decode TinyURL

### LINKED ISSUE #78: 4. Encode and Decode TinyURL (HASHING)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Hashing-> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
[https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be](https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be)

### PR DESCRIPTION
**Pull request by Sanskriti2401**
Fixes #78 

Code added for Encode and Decode TinyURL in C++.

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@Debashish-hub Kindly review my PR under LGMSOC'21

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Please add Input and output to the code @Sanskriti2401

**Comment by Sanskriti2401** [comment]
@Debashish-hub Sir,its there in the end .

**Comment by Debashish-hub** [comment]
> @Debashish-hub Sir,its there in the end .

Add one more

**Comment by Sanskriti2401** [comment]
> > @Debashish-hub Sir,its there in the end .
> 
> Add one more
 Done sir

**Review by Debashish-hub — APPROVED** [review]

**Pull request merged**
