### PR TITLE
Number_Complement.java

### LINKED ISSUE #58: 5. Number Complement (BIT-MANIPULATION)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation--> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
[https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be](https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be)

### PR DESCRIPTION
**Pull request by 2000shivam659**
Fixes #58 
Java solution for "Number Complement".

### CODE REVIEW

**Comment by ujju20** [comment]
Keep up the good work 👍🏻

**Comment by 2000shivam659** [comment]
@ujju20 Please add labels.

**Comment by ujju20** [comment]
> @ujju20 Please add labels.

What labels?

**Comment by 2000shivam659** [comment]
@ujju20 I mean levels i.e., Level-2.

**Comment by 2000shivam659** [comment]
I think if you do not add levels then it will not be counted towards my points. @ujju20

**Pull request merged**
