### PR TITLE
Search a 2D matrix

### PR DESCRIPTION
**Pull request by 23-24**
My code for the problem in c++

### CODE REVIEW

**Comment by 23-24** [comment]
@sameeksharl can u check my PR

**Comment by sameeksharl** [comment]
@23-24 you cant proceed until its been assigned , initially you have to ask mentors for the work to get assigned and then
 you can start working on it . Do check out the video for more info .

**Comment by 23-24** [comment]
@sameeksharl I have asked for the issue by commenting under it first.

**Comment by 23-24** [comment]
I have also specified the language

**Comment by 23-24** [comment]
you said to work on it

**Pull request closed without merging**
