### PR TITLE
Create 4_Excel_Sheet_Column_Name.cpp under LGMSOC21

### LINKED ISSUE #90: 4. Excel Sheet Column Title (MATH)
Contribution Guidelines for this question

-Languages available: C++, Java, Python
-Well Commented Code
-In the starting, add a brief explanation of the algorithm
-if possible, add time and space complexity
-kindly upload your code in MATH -> Language (C++, Java, Python) Folder
-NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

### PR DESCRIPTION
**Pull request by AtrikGit6174**
Fixes #90
@YashThakare Kindly check.

### CODE REVIEW

**Review by YashThakare — COMMENTED** [review]
Hi @AtrikGit6174 , Problem Statement is - Excel Sheet Column Title and not Excel Sheet Column Number . Both are different problems . Please check it

**Review by YashThakare — CHANGES_REQUESTED** [review]
Hi @AtrikGit6174 , Problem Statement is - Excel Sheet Column Title and not Excel Sheet Column Number . Both are different problems . Please check it.

**Comment by AtrikGit6174** [comment]
Okay sure, I will check the problem again.
As I previously pointed out, it is really cumbersome to go back to the Directories to check the PS... Can we please have the link in the issues too?

**Comment by YashThakare** [comment]
> Okay sure, I will check the problem again.
> As I previously pointed out, it is really cumbersome to go back to the Directories to check the PS... Can we please have the link in the issues too?

You can refer the problem statement link from Math->README.md
Link- https://leetcode.com/problems/excel-sheet-column-title/

**Comment by AtrikGit6174** [comment]
I will generate a new PR for this issue and am closing this one. Looks like I am messing up a few things.

**Pull request closed without merging**
