### PR TITLE
Last Stone Weight

### LINKED ISSUE #72: 3. Last Stone Weight (HEAP)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Heap -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
[https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be](https://www.youtube.com/watch?v=Ff38VOjv1no&feature=youtu.be)

### PR DESCRIPTION
**Pull request by Sanskriti2401**
Fixes #72 
Code added for Last Stone Weight in C++.

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@Debashish-hub Kindly review my PR

**Comment by vilsi12** [comment]
Please add the time complexity

**Comment by Sanskriti2401** [comment]
@vilsi12 Done

**Comment by vilsi12** [comment]
Do run this program it not working

**Comment by Sanskriti2401** [comment]
@vilsi12 The program is working and got submitted in leetcode. 
Actually the test case is not in right order. I have edited it.
Please check it now

**Pull request closed without merging**
