### PR TITLE
Counting bits of a number using Java

### LINKED ISSUE #57: 4.Counting Bits of a Number(BIT-MANIPULATION)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation--> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

### PR DESCRIPTION
**Pull request by anushka-srivastava22**
Fixes #57 

Add a Program as new Feature

Follows all guidelines of readme file.

### CODE REVIEW

**Review by ujju20 — CHANGES_REQUESTED** [review]
Add a serial number of question to file name.
The serial number of questions is mentioned in the readme.md file of respective topic

**Comment by anushka-srivastava22** [comment]
Okay @ujju20

**Comment by ujju20** [comment]
> Okay @ujju20

You haven't the done task?

**Comment by anushka-srivastava22** [comment]
I have done this and created another pull request which you merged earlier.

**Pull request closed without merging**
