### PR TITLE
5. Count the number of consistent strings (HASHTABLE)

### PR DESCRIPTION
**Pull request by soma2000-lang**
#64
code done in c++

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  pleasee check

**Comment by Sargam-Agarwal** [comment]
Hey @soma2000-lang,
Kindly fulfill all the requirements of the codebase as mentioned in the README. 
Please take care of these things while contributing.

**Review by Sargam-Agarwal — CHANGES_REQUESTED** [review]
Kindly add the main function and other requirements as per the codebase.

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  done

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  please merge

**Comment by Sargam-Agarwal** [comment]
Hey @soma2000-lang,
Kindly add the header files as well. How come your code is running without header files !?

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  done

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal If this one gets merged can u please assign me #62

**Comment by Sargam-Agarwal** [comment]
Sorry @soma2000-lang, but it doesn't seem like you are doing these codes by yourself. Do you think these header files are enough to run your code correctly ? 
I will see to this code only now. I wont be assigning you any issue from now on.
Find the mistake. Rectify it if possible. Ill merge this one.

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal I think this header file will suffice #include <bits/stdc++.h>

**Comment by Sargam-Agarwal** [comment]
@soma2000-lang,
Merging it.

**Pull request merged**
