### PR TITLE
Nth digit

### PR DESCRIPTION
**Pull request by soma2000-lang**
#199 
Code done in c++

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@YashThakare  please check

**Review by YashThakare — CHANGES_REQUESTED** [review]
Hi @soma2000-lang , Please don't copy code from leetcode. Plagiarism is strictly not allowed. Please go through README file.

**Comment by soma2000-lang** [comment]
@YashThakare  Actually i was stuck in this problem and  the deadline  is 1 day.Thats why I just took help from leetcode.But I have understood the problem.

**Comment by YashThakare** [comment]
> @YashThakare Actually i was stuck in this problem and the deadline is 1 day.Thats why I just took help from leetcode.But I have understood the problem.

Hi @soma2000-lang , Okay Please change the code . I have checked other PRs also of yours and in that also you have copy pasted the code from leetcode only . Please go through README file once.

**Comment by soma2000-lang** [comment]
@YashThakare  I have expalined each and every line in the code in my own words

**Comment by YashThakare** [comment]
> @YashThakare I have expalined each and every line in the code in my own words

Hey @soma2000-lang , Please change the code. Plagiarism is strictly not allowed. Please go through README file.

**Comment by soma2000-lang** [comment]
Ok

**Comment by soma2000-lang** [comment]
@YashThakare  check now

**Comment by YashThakare** [comment]
> @YashThakare check now

@soma2000-lang , Please change the code . You have just changed the variable name.

**Comment by YashThakare** [comment]
Hi @soma2000-lang , Please do the required changes in the code.

**Comment by soma2000-lang** [comment]
@YashThakare  please check

**Review by YashThakare — CHANGES_REQUESTED** [review]
@soma2000-lang , Please fix the typo errors. Code is perfect.

**Comment by soma2000-lang** [comment]
@YashThakare  check now.If this one gets merged then please assign me 9. Interleaving String (DYNAMIC PROGRAMMING) 
#196

**Pull request merged**
