### PR TITLE
power of 2

### PR DESCRIPTION
**Pull request by nisha331**
issue #56

### CODE REVIEW

**Comment by ujju20** [comment]
Keep up the good work 👍🏻

**Review by ujju20 — CHANGES_REQUESTED** [review]
Hey, @nisha331  you have to include at least two example test cases at the end of your code.

**Comment by ujju20** [comment]
Keep up the good work 👍🏻

**Comment by ujju20** [comment]
I am merging your PR but just a suggestion make PR from a different branch-like don't commit to the main branch of your forked repo.

**Comment by nisha331** [comment]
Okh Thanks @ujju20 will take care of that in the next PR

**Comment by ujju20** [comment]
> Okh Thanks @ujju20 will take care of that in the next PR

Ya  Keep coding! 😃

**Pull request merged**
