### PR TITLE
5. Best Time to Buy and Sell Stock (DYNAMIC PROGRAMMING)

### PR DESCRIPTION
**Pull request by soma2000-lang**
Done in C++
 #84

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@YashThakare  please check

**Review by YashThakare — CHANGES_REQUESTED** [review]
Hi @soma2000-lang , please write main function. Also check typo mistake in time complexity part.

**Comment by soma2000-lang** [comment]
@YashThakare  check now

**Review by YashThakare — CHANGES_REQUESTED** [review]
Hi @soma2000-lang , Please add one more example.

**Comment by soma2000-lang** [comment]
@YashThakare  done

**Review by YashThakare — CHANGES_REQUESTED** [review]
@soma2000-lang , Please include header files. This program contains variable scope errors . Please fix it.

**Comment by soma2000-lang** [comment]
@YashThakare header files included but if run this program withiout the main function it will run completely fine

**Comment by YashThakare** [comment]
> @YashThakare header files included but if run this program withiout the main function it will run completely fine

@soma2000-lang Yes I know that . Just create a class object in main function and call function using that object. Please do the required changes.

**Comment by soma2000-lang** [comment]
@YashThakare  please check now

**Review by YashThakare — CHANGES_REQUESTED** [review]
@soma2000-lang , Program has lot of errors . Please check and resolve all errors at once.

**Comment by YashThakare** [comment]
Hey @soma2000-lang , Please do the required changes to solve the errors.

**Comment by soma2000-lang** [comment]
@YashThakare  giving no errors now

**Review by YashThakare — CHANGES_REQUESTED** [review]
Hi @soma2000-lang , Logical error - Please assign value to N from user input . It is by default taking 0 as value if you don't initialize it . Please check your programs with some examples first and dry run it . 
Also merging conflict is there . Try to fix it.

**Comment by YashThakare** [comment]
Hi @soma2000-lang , Please check and resolve all errors at once.

**Comment by soma2000-lang** [comment]
@YashThakare tHIS IS SHOWING-
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

**Comment by YashThakare** [comment]
> @YashThakare tHIS IS SHOWING-
> This branch has conflicts that must be resolved
> Only those with write access to this repository can merge pull requests.
> 
> ANd the program is running succesfully now with correct oututs

Hi @soma2000-lang , that is because you have added 2-3 files in one PR (Relative_Ranks file) . Please fix that issue of Merge Conflict or else create a New Pull Request for this question .

**Comment by soma2000-lang** [comment]
> > @YashThakare tHIS IS SHOWING-
> > This branch has conflicts that must be resolved
> > Only those with write access to this repository can merge pull requests.
> > ANd the program is running succesfully now with correct oututs
> 
> Hi @soma2000-lang , that is because you have added 2-3 files in one PR (Relative_Ranks file) . Please fix that issue of Merge Conflict or else create a New Pull Request for this question .

No I have created seperate prs only as u can see the branch names of all my PR are different

**Pull request closed without merging**
