### PR TITLE
Added Counting Bits in C++

### LINKED ISSUE #57: 4.Counting Bits of a Number(BIT-MANIPULATION)
# Contribution Guidelines for this question

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation--> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

### PR DESCRIPTION
**Pull request by mrkc2303**
I have added the problem- Counting Bits using C++ using BIT MANIPULATION.
This resolves #57

### CODE REVIEW

**Comment by mrkc2303** [comment]
Kindly review it @YashThakare @ujju20

**Comment by vilsi12** [comment]
@mrkc2303 dont write in leetcode you have start it from class directly it don't run in simple ide

**Review by ujju20 — CHANGES_REQUESTED** [review]
First of all, write the full code including headers, etc and add the test case at the bottom of the code.

**Comment by mrkc2303** [comment]
@ujju20 @vilsi12 
Sure, I will make the changes requested and get back to you within a day. 
Thank You

**Comment by ujju20** [comment]
> @ujju20 @vilsi12
> Sure, I will make the changes requested and get back to you within a day.
> Thank You

Any Updates @mrkc2303 ??

**Comment by ujju20** [comment]
> @ujju20 @vilsi12
> Sure, I will make the changes requested and get back to you within a day.
> Thank You

@mrkc2303 Are your working on this or should I close this PR?

**Comment by mrkc2303** [comment]
@ujju20 
Hi, sorry for the delay. Due to personal medical issues it took me time to change the code. 
Please let me do it. Will try to get it done by today. 

Really sorry for the Inconvenience!

**Comment by ujju20** [comment]
> @ujju20
> Hi, sorry for the delay. Due to personal medical issues it took me time to change the code.
> Please let me do it. Will try to get it done by today.
> 
> Really sorry for the Inconvenience!

It's Ok I just wanted to know that you will do it or not. If you are doing it then fine.

**Comment by mrkc2303** [comment]
@ujju20 
Kindly Check.
Let me know if any changes required.
Sorry for the delay :)

**Comment by ujju20** [comment]
> @ujju20
> Kindly Check.
> Let me know if any changes required.
> Sorry for the delay :)

You have to add an explanation to the code using comments.

**Comment by mrkc2303** [comment]
@ujju20 
Kindly Check Now!

**Pull request merged**
