### PR TITLE
Revert "Nth digit"

### PR DESCRIPTION
**Pull request by YashThakare**
Reverts LetsGrowMoreCommunity/DSA-Playyard#258

Hi @soma2000-lang , Please explain your approach at start the code.

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@YashThakare  the edit option is disabled how should I explian it now

**Comment by YashThakare** [comment]
> @YashThakare the edit option is disabled how should I explian it now

Ok @soma2000-lang, Please create a new PR for it then.

**Comment by YashThakare** [comment]
Hi @soma2000-lang , Please do the suggested changes.

**Comment by soma2000-lang** [comment]
@YashThakare  i have made a new pr please check

**Comment by YashThakare** [comment]
Ok @soma2000-lang

**Pull request closed without merging**
