### PR TITLE
5. Count the number of consistent strings (HASHTABLE) 

### PR DESCRIPTION
**Pull request by soma2000-lang**
Done the code in c++
#64

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  Please Check

**Comment by Sargam-Agarwal** [comment]
Hey @soma2000-lang 
The code looks fine. But kindly go through the README. In it, its clearly mentioned what all your codebase should contain. The first three requirements are missing. Fix those points, then will merge your code 👍

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  Please check now

**Comment by Sargam-Agarwal** [comment]
Hey @soma2000-lang 
Code is good now but your PR still has other 2 code files. Kindly delete those. Just keep the Consistent strings one. Let me see then if it works fine because as of now it shows that this commit cannot be merged...it has some conflicts.

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  I have deleted thse 2 files
I cannot resolve the conflict,

**Comment by Sargam-Agarwal** [comment]
On my end it shows, conflicting files is Heap/C++/4_Relative Ranks.cpp. 
@soma2000-lang 

See to it and let me know accordingly now. Otherwise we'll see to it what can be done next 👍

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal  while cntributing to other projects also I faced the issue .But it is to be resolves by the the mentors(bascically the ones who merges).on my systen its showing-
"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
Heap/C++/4_Relative Ranks.cpp"

**Comment by Sargam-Agarwal** [comment]
Okk let me check if something is possible from my end 👍

**Comment by Sargam-Agarwal** [comment]
Hey @soma2000-lang,
The way you have contributed has created a lot of chaos. Your solution for this question and also for the question Buy and Sell Stocks cannot be merged. I had a talk with the mentor for that question as well. Its creating conflicts. 
So, kindly close both the PRs. Create new issues and please this time create separate PRs for each code.

**Comment by soma2000-lang** [comment]
@Sargam-Agarwal I had created   a seperate  only.I think the reason it has shown conflicting files happens when anyone's files gets merged after my cloning  the repo.As u can see I created seperate branches for both this question and Buy and sell stock one ,so that the conflict is not there.

**Pull request closed without merging**
