### PR TITLE
Create 2_Search_a_2D_Matrix

### LINKED ISSUE #128: 2. search-a-2d-matrix(ARRAYS)
Contribution Guidelines for this question-

-Languages available: C++, Java, Python
-Well Commented Code
-In the starting, add a brief explanation of the algorithm
-if possible, add time and space complexity
-kindly upload your code in ARRAYS -> Language (C++, Java, Python) Folder
-NO PLAGIARISM
https://youtu.be/qXeaN_ZVVIc

### PR DESCRIPTION
**Pull request by khushi-purwar**
Fixes #128

### CODE REVIEW

**Comment by khushi-purwar** [comment]
@sameeksharl Kindly Check my PR

**Comment by SnehaAgarwal361** [comment]
The time complexities seem correct to me, nice work.
Keep coding!

**Comment by khushi-purwar** [comment]
Hey @SnehaAgarwal361, In DSA-Playyard,, PR's will not get the level tag?

**Comment by SnehaAgarwal361** [comment]
Done:)

**Pull request merged**
