### PR TITLE
Java solution "Find the Duplicate Number "

### LINKED ISSUE #208: 10. Find the Duplicate Number (BIT-MANIPULATION)
# Contribution Guidelines for this question-

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

### PR DESCRIPTION
**Pull request by 2000shivam659**
Fixes #208 
Please review it.

### CODE REVIEW

**Review by ujju20 — CHANGES_REQUESTED** [review]
Your Code is commented Uncomment it.

**Comment by 2000shivam659** [comment]
what do you mean by comment ? Please elaborate @ujju20

**Comment by ujju20** [comment]
> what do you mean by comment ? Please elaborate @ujju20

I mean to say that your code is written in comments just like you write comments.
Uncomment it.

**Comment by ujju20** [comment]
> > what do you mean by comment ? Please elaborate @ujju20
> 
> I mean to say that your code is written in comments just like you write comments.
> Uncomment it.

Oh sorry, You have to name your file like this filename.cpp

**Comment by ujju20** [comment]
Any Updates @2000shivam659 ??

**Comment by 2000shivam659** [comment]
Please check now @ujju20

**Comment by ujju20** [comment]
Keep Coding 👍🏻

**Pull request merged**
